name:                jsonpath
version:             0.1.0.0
github:              "akshaymankar/jsonpath-hs"
license:             BSD3
author:              "Akshay Mankar"
maintainer:          "itsakshaymankar@gmail.com"
copyright:           "Akshay Mankar"

extra-source-files:
- README.md
- ChangeLog.md
- test/resources/json-path-tests/*.json

# Metadata used when publishing your package
synopsis:            Library to parse and execute JSONPath
category:            Text, Web, JSON

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/akshaymankar/jsonpath-hs#readme>

tested-with: GHC == 8.0.2, GHC == 8.2.2, GHC == 8.4.4, GHC == 8.6.4

dependencies:
- aeson                >= 1.4.2 && < 1.5
- attoparsec           >= 0.13.2 && < 0.14
- base                 >= 4.9 && < 5
- text                 >= 1.2.3 && < 1.3
- unordered-containers >= 0.2.10 && < 0.3
- vector               >= 0.12.0 && < 0.13

library:
  source-dirs: src

tests:
  jsonpath-test:
    main:                Spec.hs
    source-dirs:         test
    build-tools:         hspec-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson-casing
    - bytestring
    - file-embed
    - hspec
    - hspec-attoparsec
    - jsonpath
